### ISSUE TITLE
Programmatically trigger the display of swipe actions

### ISSUE THREAD

**Issue by Awalz** [jerkoch/SwipeCellKit#13]
Hey,

Im looking for a manual way to trigger showing the editing options. In particular, I would like to show editing options when didSelectRowAtIndex is called. I see there is support for ```hideSwipe(animated:)```, but I don't see an option for any ```showSwipe(animated:)```. Is it possible? Thanks

Andrew

**Comment by jerkoch** [comment]
Hey @Awalz - Yep, that should be pretty straightforward to add. I'll try to take a look at it in the next few days.

**Comment by Awalz** [comment]
Thanks for looking into this so quickly!.

Is version 1.5.0 live yet?

Andrew

**Comment by jerkoch** [comment]
Hi @Awalz - No problem! 😀

I have a few more things lined up for the next release which I'm planning to ship soon. In the meantime, if you're using CocoaPods, see the Installation instructions in the README to pull directly from the develop branch.
