### ISSUE TITLE
Swipe Delete Animation Appearing on wrong TableViewCell

### ISSUE THREAD

**Issue by Awalz** [jerkoch/SwipeCellKit#15]
I am currently implementing a Swipe to delete feature to my tableview. In some cases, the delete animation will finish on the incorrect line, resulting in a strange animation. My implementation is pretty bare: 
```swift
func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        if orientation == .right {
            let deleteAction = SwipeAction(style: .destructive, title: nil) { (action, indexPath) in
                self.currentDishes.remove(at: indexPath.row)
            }
            deleteAction.backgroundColor = CDColor.red
            deleteAction.image           = #imageLiteral(resourceName: "trash_small")
            return [deleteAction]
        } else {
            return nil
        }
    }
    
func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {
        var options = SwipeTableOptions()
        options.expansionStyle  = orientation == .left ? .destructive : .destructive
        options.transitionStyle = .border
        return options
}
```

Here is a GIF  I captured of it occurring:

![naivezestygalah](https://cloud.githubusercontent.com/assets/8753566/23814330/61f5c464-05a0-11e7-848c-82f32335a35c.gif)

[Slow speed](https://gfycat.com/NaiveZestyGalah#?speed=0.125)

Let me know if you have any advice

Andrew

**Comment by Awalz** [comment]
I believe I have narrowed down the issue. It only occurs when the cell being deleted is larger than the cells below it, and if the combined height of the cells below the deleted cell is less than the height of the deleted cell.

Andrew

**Comment by jerkoch** [comment]
Hey @Awalz - Thanks for the detailed issue description - slowmo gives us a hint at what is happening.  

It looks like the cell being deleted is getting reused as the new cell that is coming in from the bottom.  The table view has no idea that the animated expansion is still finishing when reuse occurs.  

Can you provide a simple sample project that demonstrates this issue?

**Comment by jerkoch** [comment]
Hey @Awalz - Scrap what I said in my previous comment 😀

I think it might be because there are not enough cells below the deleted row to animate up and cover the expansion animation. Is the "Eggs Benedict" row the last row in your table view?

**Comment by Awalz** [comment]
Yes it is.

This issue occurs if the UITableViewCell's height you are deleting is greater than the height of the remaining cells below it. I can put together a sample project when I get home tomorrow, but it should be easily reproducible 

Andrew

**Comment by jerkoch** [comment]
Hey @Awalz - Can you try [bug/15-delete-animation](/jerkoch/SwipeCellKit/tree/bug/15-delete-animation) branch and let me know if that fixes this for you?

**Comment by Awalz** [comment]
I just tested it. I can no longer reproduce the bug. It appears to be resolved. I will continue to test

Andrew
