### ISSUE TITLE
Swipe cell with accessory doesn't call accessoryButtonTapped

### ISSUE THREAD

**Issue by Jonge** [jerkoch/SwipeCellKit#16]
Hey,

I have a custom cell (subclass of `SwipeTableViewCell`). When I add an accessory view using `cell.accessoryType = .detailButton`, the method `tableView(_ tableView: UITableView, accessoryButtonTappedForRowWith indexPath: IndexPath)` doesn't get called.

When using a subclass of `UITableViewCell`, it all works fine, so pretty sure it's a bug.

Do you need a sample project or is it fine like this?

Thanks for the great library!

**Comment by jerkoch** [comment]
Hey @Jonge - Nice catch!  Standby for a fix.

**Comment by jerkoch** [comment]
Apparently `UITableViewCell` implemented some important behavior in `didMoveToSuperview()`.  😜

**Comment by Jonge** [comment]
Amazing, thanks for the quick fix! 👍
