### ISSUE TITLE
Enable the use of tableView(willBeginEditingRowAt:), etc.

### ISSUE THREAD

**Issue by dricard** [jerkoch/SwipeCellKit#18]
Make SwipeCellKit invoke the methods `tableView(willBeginEditingRowAt:)` and `tableview(didEndEditingRowAt:)`.

**Comment by jerkoch** [comment]
Hey @dricard - Thanks for reminding me about this one.  I'll take a look at it soon.   I'm not sure if we should be calling existing table view delegate methods, or create similar ones on `SwipeTableViewCellDelegate`.  

Opinions?

**Comment by dricard** [comment]
My first thought would be to call the existing tableview delegate methods but I don't know if that would break things with the `SwipeTableViewDelegate`. My main use for this is that I have running animations in some cells, and when the user starts a swipe I need to pause the animation (on `willBeginEditingRowAt` and resume on `didEndEditingRowAt:`.

**Comment by jerkoch** [comment]
Hey @dricard - I had to change the delegate method names to resolve an issue with `UITableViewController`. Please see  95889a1 commit details for a better explanation.

**Comment by dricard** [comment]
@jerkoch I tested that and it works great in my context. Thanks!
