### ISSUE TITLE
Feature request: Bounce cell to reveal actions

### ISSUE THREAD

**Issue by pepejeria** [jerkoch/SwipeCellKit#19]
Swipe actions are not always easy to discover by users. It would therefore be nice to have SwipeCellKit provide an easy mechanism to bounce a selected cell after x seconds to make the swipe discoverable.

**Comment by jerkoch** [comment]
Hi @pepejeria - This would probably best be addressed by a `swipeOffset` property and a`setSwipeOffset(animated:)` method.  That should give enough flexibility to the app to bounce however it needs.  

Thoughts?

**Comment by pepejeria** [comment]
Hi @jerkoch, sounds good. I guess this would work for both orientations right?

**Comment by jerkoch** [comment]
Good point. Two options that I can see:

1.  A negative offset would expose right-side actions, and a positive offset would expose left-side actions. 

2. `setSwipeOffset(offset:orientation:animated:)` would be clearer but retrieving the current swipe offset wouldn't work as a single property.

I'll think some more about it.

**Comment by Uupis** [comment]
Would wrapping the offset in an `SwipeOffset` enum be a viable solution? It seems to be an OK case for an enum – the two directions are mutually exclusive.

Something along the lines of:
```swift
enum SwipeOffset {
  case left(distance: UInt)
  case right(distance: UInt)

  func changed(to newDistance: UInt) -> SwipeOffset {
    switch self {
    case .left:
      return .left(distance: newDistance)
    case .right:
      return .right(distance: newDistance)
    }
  }

  mutating func change(to newDistance: UInt)  {
    self = changed(to: newDistance)
  }
}
```

**Comment by jerkoch** [comment]
Hey @Uupis - Good idea. I think it could work!  👍

Probably should add a `.center` case without an associated value, which would be the equivalent of `.left(0)` or `.right(0)`.  And also a computed `distance` property that simply returns the `UInt` in cases where `left` or `right` isn't relavent.

I'll play around with this a bit when I get a chance.

**Comment by jerkoch** [comment]
Hi @Uupis - I scraped the `.center` idea since things got dicey trying to support `+` and `-` operators.   Here's where I landed:

```swift
public enum SwipeOffset: Equatable {
    case left(distance: Int)
    case right(distance: Int)

    public var distance: Int {
        switch self {
        case let .left(distance): return distance
        case let .right(distance): return distance
        }
    }
    
    public static func ==(lhs: SwipeOffset, rhs: SwipeOffset) -> Bool {
        switch (lhs, rhs) {
        case (let .left(distance1), let .left(distance2)): return distance1 == distance2
        case (let .right(distance1), let .right(distance2)): return distance1 == distance2
        default: return false
        }
    }
    
    public static func +(lhs: SwipeOffset, rhs: Int) -> SwipeOffset {
        switch lhs {
        case let .left(distance): return .left(distance: distance + rhs)
        case let .right(distance): return .right(distance: distance + rhs)
        }
    }
    
    public static func -(lhs: SwipeOffset, rhs: Int) -> SwipeOffset {
        switch lhs {
        case let .left(distance): return .left(distance: distance - rhs)
        case let .right(distance): return .right(distance: distance - rhs)
        }
    }
}
```

**Comment by Uupis** [comment]
Hey @jerkoch – looks good!

**Comment by Mutix** [comment]
👍 I was thinking this would be useful for my implementation too. 

Happy to help out building the feature if needed.

**Comment by jerkoch** [comment]
Hey @Mutix - Thanks for the offer! 🍻 

I had already started on this when I got sidetracked with a few other pull requests.  I'm hoping to get it finished this weekend.  If that doesn't happen, I'll gladly reach back out to you for help!

**Comment by pepejeria** [comment]
Thank you for implementing this, could you please provide an example how to slightly bounce the cell like iOS 6-7 did to reveal the camera on the home screen?

**Comment by pepejeria** [comment]
Sorry, I see now that setting a negative offset is required to expose the right side.

**Comment by nameghino** [comment]
Is there any way of not triggering the willStart/didEnd delegate callbacks when using this? I need to tell if the user initiated the swipe or it's the programmatic setSwipeOffset(). Is there any other way of doing this?
