### ISSUE TITLE
Locking swiping from the left triggers prevention of Action

### ISSUE THREAD

**Issue by abokhalel2** [jerkoch/SwipeCellKit#2]
Hi,

First, thank you for this awesome kit!

I have one small issue. In my implementation of this kit, I used the provided code to cancel the left swipe:
`guard orientation == .right else { return }`

However, this code triggers this error in Xcode 8.2.1:
Non-void function should return a value

I fixed this error by adding `[ ]`:
`guard orientation == .right else { return [] }`

This worked fine as it locked swiping from left, however, I noticed that when someone tries to swipe from the left, (no action is taken), then swipes from the right on the same cell or tap on it, no action is taken too. If he swipes/taps again, then, the right swipe action or the tab action works fine.

Is there a way to make this locked left swipe does not cause this temporary prevention of action?

Thank you

**Comment by jerkoch** [comment]
Hey @abokhalel2 - Yep, that's a bug!  I did most of my testing with actions on both sides, so I never ran across this myself.  I'm going to also update the `editActionsOptionsForRowAt` delegate call to return an optional array of `SwipeAction`, that way your guard statement can return nil instead of the empty array.

**Comment by abokhalel2** [comment]
Thank you @jerkoch. Looking forward to the new update 👍

**Comment by jerkoch** [comment]
Thanks for raising this @abokhalel2 

I'll try and get to this in the next few days and release 1.2.0

**Comment by jerkoch** [comment]
Hey @abokhalel2 - Can you verify the new behavior is as you expect?  I'll cut the release once confirmed.

**Comment by abokhalel2** [comment]
Yes, It is now working as expected. Thank you so much.
