### ISSUE TITLE
Pull down/Release on cell with SwipeAction buttons visible removes background colors?

### ISSUE THREAD

**Issue by seenoevo** [jerkoch/SwipeCellKit#21]
**1.** 
I have 3 SwipeAction buttons with different background colors.

If all the SwipeAction buttons are visible, and I pull down on the area of the cell not covered by the SwipeAction buttons, i.e. the lighter area on the left, then release my finger, this momentarily causes all the SwipeAction button backgrounds to become clear like so:"

![untitled](https://cloud.githubusercontent.com/assets/8109158/24221170/773b8fde-0f0a-11e7-9705-bec5c8603eff.png)
 
After half a second, it returns back to the normal assigned background colors.

**2.** 
The SwipeAction buttons doesn't retract back to the right.

Are both this things suppose to occur or is this a bug?

**Comment by jerkoch** [comment]
Hi @seenoevo - Very strange!  Can you attach a simple sample project demonstrating the issue?

**Comment by seenoevo** [comment]
[Dry Cleaners Reminder copy 2.zip](https://github.com/jerkoch/SwipeCellKit/files/865213/Dry.Cleaners.Reminder.copy.2.zip)

please test it out @jerkoch

**Comment by seenoevo** [comment]
@jerkoch to help you further debug this, this issue only occurs if I have the cell's **Selection** to anything but None.

If the cell can be tapped, then this issue occurs.

I set the cell's selection to None, and the issue does not occur anymore.
