### ISSUE TITLE
Unwind Segue causes SwipeAction button menu to disappear

### ISSUE THREAD

**Issue by seenoevo** [jerkoch/SwipeCellKit#23]
@jerkoch I just found a bug where, if using a UINavigationController, if the SwipeAction menu is currently opened when another View Controller is pushed onto the stack, then an unwind segue is performed back to the main View Controller, the SwipeAction menu buttons disappear.

To get the SwipeAction menu to show again, you have to swipe left on that cell.

Here's a screenshot:

Before Unwind Segue:
![fullsizerender](https://cloud.githubusercontent.com/assets/8109158/24327746/085d90f4-118e-11e7-9032-7232739a63c6.jpg)

After Unwind Segue:
![fullsizerender-2](https://cloud.githubusercontent.com/assets/8109158/24327747/100c8d50-118e-11e7-8e77-341e23b71f55.jpg)

Currently, the only fix I can across is to reload the tableview in whatever function returned from when an Unwind segue occurs so that the SwipeAction menu disappears.

**Comment by seenoevo** [comment]
thanks @jerkoch for both bug fixes, however there is a new issue

originally I had the following set up:

```
    func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions
    {
        var options = SwipeTableOptions()
        
        options.expansionStyle = .none
        options.transitionStyle = .border
        options.maximumButtonWidth = 0
        options.buttonPadding = 0
        
        return options
    }
```

However, with the new bug fixes, .border does not collapse the SwipeAction buttons, but it looks to be .reveal.

Also, the `expansionStyle` of `.none` does not work as illustrated, I feel like it's a combination of selection and destructive.

Here's a sample project illustrating what I mean:

[Test.zip](https://github.com/jerkoch/SwipeCellKit/files/877709/Test.zip)

**Comment by jerkoch** [comment]
Hey @seenoevo - Thanks for finding this!  You caught the one setup that I didn't try.  😕

Standby for a fix!

**Comment by seenoevo** [comment]
@jerkoch issue fixed

thanks for the quick update and support

I'll let you know if I find any other bugs :)
