### ISSUE TITLE
`expansionStyle` selection doesn't work well with 2+ actions

### ISSUE THREAD

**Issue by MaxHasADHD** [jerkoch/SwipeCellKit#24]
Having a `expansionStyle` set to `selection` doesn't work well if there are multiple actions. The actions fill more than half of the screen but thats when the default action will be used. `destructive` works well but tries to delete the cell

**Comment by MaxHasADHD** [comment]
Updated framework, seems like this issue was fixed

**Comment by jerkoch** [comment]
Hey @MaxHasADHD - Yep, fixed this one a few versions ago!

If you need more control over expansion, like customizing where expansion should trigger, take a look at the [expansion](/jerkoch/SwipeCellKit/tree/expansion) branch.  I'll be merging it into master shortly after a bit more testing.
