### ISSUE TITLE
Missing actions

### ISSUE THREAD

**Issue by khambir** [jerkoch/SwipeCellKit#27]
I have cell with right and left actions.
Left actions have "fill" expansionStyle and Right have "destructive" expansionStyle.
When left action was performed, the right actions are invisible, I can swiping the cell, actions is performing, but actions button are invisible.

**Comment by jerkoch** [comment]
Thanks @khambir.  I'll take a look at this soon!

**Comment by khambir** [comment]
Bug is not fixed.

I have 2 buttons:
![screen shot 2017-04-07 at 3 56 43 pm](https://cloud.githubusercontent.com/assets/12631113/24800962/f64e08fe-1baa-11e7-896e-85701939b861.png)

I call left action with expansionStyle .fill 
![screen shot 2017-04-07 at 3 57 11 pm](https://cloud.githubusercontent.com/assets/12631113/24800963/f6705b84-1baa-11e7-8ec5-221e79e29a11.png)

Buttons from right were missing.
![screen shot 2017-04-07 at 3 57 33 pm](https://cloud.githubusercontent.com/assets/12631113/24800964/f67219b0-1baa-11e7-8492-364a3a51a880.png)

**Comment by jerkoch** [comment]
Hey @khambir - Can you confirm you're using the latest from the develop branch?

**Comment by khambir** [comment]
Yes, I updated pod from the develop branch. And double checked, your changes did appear in my project.

**Comment by jerkoch** [comment]
Hmm... 🤔

It seems like the mask is still not getting reset somehow. Can you paste your relevant delegate code or provide a small sample project?

**Comment by khambir** [comment]
[swipeProject.zip](https://github.com/jerkoch/SwipeCellKit/files/905775/swipeProject.zip)

**Comment by jerkoch** [comment]
Hey @khambir - The issue was that you're not called `action.fulfill(style: .reset)` from your action handler. Fill expansions aren't autofulfilling.  See the README for more details.  

I made a change that will fix this even if you don't call `action.fulfill(style: .reset)`, but you should still add it on your end.  👍
