### ISSUE TITLE
Calls to UITableView.beginUpdates/endUpdates hide swipe actions 

### ISSUE THREAD

**Issue by tschmitz** [jerkoch/SwipeCellKit#28]
I'm running into an issue where calls to `UITableview.beginUpdates` and `UITableview.endUpdates` while action buttons are visible causes the buttons to be hidden, even if the cell in question doesn't change. That's particularly problematic when using an `NSFetchedResultsController`. Is there a setting that I'm missing that changes this behavior?

**Comment by jerkoch** [comment]
Hey @tschmitz - This is an interesting one!  🤔

When `UITableView.endUpdates()` is called, the `UITableView` is updating all its `UITableViewCell` subview frames in `layoutSubview()`.  Although I don't like the idea is overriding the cell's `frame` setter and adjusting the `newValue` if the cell state is active, I think it's the only way to deal with this issue. 

I'll commit a fix shortly.  Please give it a try and let me know if it fixes your issue.

**Comment by tschmitz** [comment]
@jerkoch Worked like a charm - thanks so much for the quick fix!
