### ISSUE TITLE
Unresponsive cell

### ISSUE THREAD

**Issue by khambir** [jerkoch/SwipeCellKit#31]
I found a bug.

1. I have custom cell, whit inherit from SwipeTableViewCell class.
2. This cell has imageView object.
3. When I try to swipe cell and my finger lies on this imageView, I have a bug - cell is unresponsive (I can not select, swipe on this cell etc.)

After that I change subclass of this custom cell from SwipeTableViewCell to UITableViewCell and everything is ok, so problem in SwipeTableViewCell class. After that I was found that bug is gone if I commented **128 line in SwipeTableViewCell class**:
```

 if state == .center || state == .animatingToCenter {
                //state = .dragging ----> It is fix bug, but I do not know why

                let velocity = gesture.velocity(in: target)
                let orientation: SwipeActionsOrientation = velocity.x > 0 ? .left : .right

                showActionsView(for: orientation)
}

```

**Comment by jerkoch** [comment]
Hey @khambir - Yuck! I tried to recreate this but haven't had much luck.  Any chance you can attach a simple sample project?

**Comment by khambir** [comment]
Try to swipe cell starting from image. And after that try to select cell, you will notice that cell is unresponsive.
Problem in SwipeTableViewCell class (128 line).

[swipeProject.zip](https://github.com/jerkoch/SwipeCellKit/files/922219/swipeProject.zip)

**Comment by jerkoch** [comment]
Hi @khambir - Thanks for the attachment! 👍  

Your sample project isn't setting the swipe `delegate` for your `CustomTableViewCell`.  You need implement at least implement the:

```swift
func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? 
```

Once I added the delegate a returned an action, I was able to swipe from anywhere.

**Comment by khambir** [comment]
This is not fully fix problem.
I have been noticed that bug appear when method

`func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]?`

returns nil.

For example, I implement method by this way:


```
   func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        guard orientation == .right else { return nil }
        let action = SwipeAction(style: .default, title: "test") { action, indexPath in
            print(indexPath)
        }
        
        return [action]
    }
```


And if orientation is .right, this method will return nil and cell is unresponsive now.
You can try to do it in current project.

**Comment by khambir** [comment]
I am glad to help :]
