### ISSUE TITLE
Decoration View

### ISSUE THREAD

**Issue by floskel** [jerkoch/SwipeCellKit#32]
Im trying to figure out if its possible to add a "decoration view" that is not the same size as the buttons. I need a smaller view between the cell content view and when the SwipeActionButtons start. 
Is this possible in any way atm?

**Comment by jerkoch** [comment]
Hey @floskel!  It's not possible without changes. 😔

I had been thinking about adding `backgroundView` and `contentInsets` properties to `SwipeTableOptions` to address #11.  This would allow you to customize the `SwipeActionsView`, which is the container view for the swipe action buttons.   In your case, setting a custom backgroundView with your decoration anchored to the side, then setting an edge inset would probably get you what you need. 

Unfortunately, I'm not sure I'll have much time to work on this right now, so feel free to take a stab at it yourself!

**Comment by floskel** [comment]
Thanks for the reply. It seems like a reasonable solution with a backgroundView and edge insets. I will look into it if i have the time. Thanks for your work!
