### ISSUE TITLE
maybe open the SwipeTableViewCell's panGestureRecognizer

### ISSUE THREAD

**Issue by awuu** [jerkoch/SwipeCellKit#33]
so I can change the isEnabled to temporary disable the gesture??

**Comment by jerkoch** [comment]
Hi @awuu - I'm interested to know why you would need direct access to the gesture recognizer?  Swiping will be disabled if you return `nil` from the `editActionsOptionsForRowAt` method in `SwipeTableViewCellDelegate`.

**Comment by awuu** [comment]
oh I return nil and it temporary disable now
forget me thanks

**Comment by nameghino** [comment]
I'm running into a similar issue: I have a cell I use in a couple of places around my app. In some view controllers, I provide actions to the swipe cell, but not in all. In a special case, a table view controller is held in a page controller, and the pan gesture recognizer for the cell is interfering with the page swipes. Now, this case is one in which I don't provide actions for the cell. 

I see that you told @awuu that returning `nil` from `editActionsOptionsForRowAt` will disable swiping, but, checking the`SwipeTableViewCell` code, I see that the gesture recognizers are not turned off or on based on this return value.

Is there any way of solving this without modifying the `SwipeTableViewCell` code? I thought of adding a property that will toggle both gesture recognizers on or off in a cell-by-cell basis.

Thanks!
