### ISSUE TITLE
Not work with Xcode 11.0

### ISSUE THREAD

**Issue by mayqiyue** [jerkoch/SwipeCellKit#355]
When I use Xcode 11.0 to build, the cell can not be swiped in iOS 13.1

**Comment by kurabi** [comment]
What version of SwipeCellKit are you using? UICollectionView or UITableView?

**Comment by mayqiyue** [comment]
SwipeCellKit: 2.7.1
UICollectionView or UITableView: UICollectionView

**Comment by SunillaShamas** [comment]
Pan gesture is working after updating pods to 2.7.1, but showSwipe(orientation) method doesnt work for me as well. 
version: 2.7.1
View: UICollectionView.

**Comment by kurabi** [comment]
I just tested with Xcode 11.0 on a 13.1 device, and example app works.

1. Please test the example mail app, report if it works or not.
2. Additionally post an example project that does not work. Please make sure no other frameworks are included.

**Comment by mayqiyue** [comment]
Sorry， it works now..
