### ISSUE TITLE
Need to override didDeleteSwipeableAt or similar

### ISSUE THREAD

**Issue by mrbodich** [jerkoch/SwipeCellKit#356]
I need to override that didDeleteSwipeableAt method to have ability to launch tableView?.deleteRows(at:) in improved way with such new code. Basically I need to reload data after removing row animation ends. But have no access to extension and even tried to edit methods inside the framework. How can I solve that or can you improve it to have such ability?

`self.tableView.performBatchUpdates({`
`                   self.tableView.insertRows(at: [IndexPath(row: self.itemsList.count - 1, section: 0)], with: .top)`
`                }) { (completion) in`
`                    self.tableView.reloadData()`
`                }`

**Comment by kurabi** [comment]
Take a look at `Advanced.md`, specifically the `Completion Animations` section to accomplish what you want.

**Comment by mrbodich** [comment]
Thank you!

**Comment by kurabi** [comment]
Thanks

Mohammad
