### ISSUE TITLE
Color below actions

### ISSUE THREAD

**Issue by ivancantarino** [jerkoch/SwipeCellKit#359]
Hello.

I have noticed that setting the `action.backgroundColor = .clear` it still looks grayish.

Does anyone know why this happens? is there a way to make it fully transparent?

Thanks.

**Comment by Ivan-Cantarino** [comment]
Hello.

I have noticed that setting the `action.backgroundColor = .clear` it still looks grayish.

Does anyone know why this happens? is there a way to make it fully transparent?

Thanks.

**Comment by JhonnyTawk** [comment]
you can solve this using :

```
var options = SwipeOptions()

options.backgroundColor = .clear
```

**Comment by ivancantarino** [comment]
@JhonnyTawk thank you 🙏 
That’s something I didn’t knew. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Baolv** [comment]
> you can solve this using :
> 
> ```
> var options = SwipeOptions()
> 
> options.backgroundColor = .clear
> ```

I have 2 SwipeAction but i just want 1 action is clear. How can do that.
