### ISSUE TITLE
Crash happened when reload tableview after delete cell

### ISSUE THREAD

**Issue by DavidHu0921** [jerkoch/SwipeCellKit#360]
I want to update my view after SwipeCell did it's delete action, and it crashed here:

```
func swipeController(_ controller: SwipeController, didDeleteSwipeableAt indexPath: IndexPath) {
        tableView?.deleteRows(at: [indexPath], with: .none)
    }
```

Here is my sample code. I know it did some animation things inside framework. Is there any delegate function to call and safety update my tableview? Please tell me, great thanks

```
func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
     let delete = SwipeAction(style: .destructive, title: nil) { action, indexPath in
            // want to reload tableview here
         }
         delete.hidesWhenSelected = true
         configure(action: delete, with: .trash)
         return [delete]
 }

 func tableView(_ tableView: UITableView, didEndEditingRowAt indexPath: IndexPath?, for orientation: SwipeActionsOrientation) {
     // or here
 }
```

**Comment by valerio-bettini** [comment]
+1

**Comment by oleksandrharmash** [comment]
+1

**Comment by DavidHu0921** [comment]
@bettola @oleksandrharmash Hi guys, after reading the code, I found that you could reload tableview before you remove sth from the datasource to avoid crash. But it causes another animation issue, I'm trying figure that out

**Comment by kurabi** [comment]
Have a look at the Expansion section of the README. You can choose to delete the row your self to coordinate this with other animations.
