### ISSUE TITLE
How to change image on swipeCell on click?

### ISSUE THREAD

**Issue by JhonnyTawk** [jerkoch/SwipeCellKit#365]
I want to be able to change the action icon and title on the click of SwipeAction without closing the cell.

`like.hidesWhenSelected = false`

When the user swipe and click on like Action I want to show the liked icon without closing the cell and also with dislike.

for further explanation: I want to change the SwipeAction icon when the user clicks on the action and the SwipeCell stills open no close

**Comment by kurabi** [comment]
You can get access of the underlying UIButton via the animation transition delegate. You can try to use that to get access to it and to change it.
