### ISSUE TITLE
Crash when deleting the last row of a section.

### ISSUE THREAD

**Issue by yunhao** [jerkoch/SwipeCellKit#366]
## What's the problem
In the example project, it demonstrates a simple email list with delete action. There is only one section and it has numerous cells. When we trigger a destructive action, SwipeCellKit will delete the row automatically by calling `tableView.deleteRows(at:with:)`. This behavior works well in the example, but it can also crash the app in a more complicated situation.

For example, we need to build a todo list with UITableView. It has multiple sections and we use date as a title for each sectoin. In each section, there are a number of rows. When we delete all rows from a section, we also want to delete the section. To do this, we have to call `tableView.deleteSections(_:with:)` by ourselves. Depending on the technology and data structure we use to drive the table veiw, sometimes it's hard for us to cooperate with SwipeCellKit.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', 
reason: 'attempt to delete row 0 from section 2, but there are only 2 sections before the update'
```

For SwipeCellKit 2.7.1, this is what we have to do temporarily:
1. Delete the last row from data source, but preserve the empty section.
2. Trigger SwipeCellKit's destructive action, it will delete the row from tableView.
3. After the action is completed, we need to delete the empty section from data source, and then delete the section from table view.

## Suggestion

I think SwipeCellKit should never call `tableView.deleteRows(at:with:)` or `tableView.deleteSections(_:with:)`, it's the developer's responsibility to determine how to modify the table.

In Apple's API(https://developer.apple.com/documentation/uikit/uicontextualaction/handler), they use a handler block for coordination.

* completionHandler
 The handler block for you to execute after you have performed the action. This block has no return value and takes the following parameter:

    * actionPerformed
A Boolean value indicating whether you performed the action. Specify true if you performed the action or false if you were unable to perform the action for some reason.

There is how we use native API to create a swipe action:

``` swift
UIContextualAction(style: .destructive, title: "Delete", handler: { action, view, completionHandler in
    if shouldDeleteCell {
        if shouldDeleteSection {
            tableView.deleteSections([indexPath.section], with: .automatic)
        } else {
            tableView.deleteRows(at: [indexPath], with: .automatic)
        }
        // The row is deleted.
        completionHandler(true)
    } else {
        // Deleting is canceled for some reason.
        completionHandler(false)
    }
})
```

Developer determines what to do with their data source and table view. The API only perform a 
corresponding animation according to the developer's choice.

**Comment by valerio-bettini** [comment]
+1

**Comment by oleksandrharmash** [comment]
+1

**Comment by kurabi** [comment]
The Expansion section in the README explains how you can delete the row instead of the framework.
