### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by alexsanderkhitev** [jerkoch/SwipeCellKit#38]
Hello! Thanks for this framework. I downloaded the sample to see how to use this framework, and found a bug. If I select a cell, that it is not read, and when I click on the Edit button, the indicator (that the cell is not read) will blend into the text.

![img_1045](https://cloud.githubusercontent.com/assets/12511909/25852989/44df6540-34dc-11e7-9fea-11811220493c.PNG)

**Comment by jerkoch** [comment]
Hey @alexsanderkhitev - I've noticed this before too! It's a bug in the sample app, not the framework.  It's related to `preservesSuperviewLayoutMargins` being set to `true`.  I'm not too concerned with it.

**Comment by alexsanderkhitev** [comment]
@jerkoch thank you so much!

Please tell me how to do so that in the editing mode, when you click on the indicator, the cell is not highlighted? Just want to know if this function or you need to implement myself. 

![img_1051](https://cloud.githubusercontent.com/assets/12511909/25865838/6c9e032e-3505-11e7-873e-11efed83935c.PNG)

**Comment by jerkoch** [comment]
Hi @alexsanderkhitev - You can set the cell's `selectionStyle` property to `.none` while in editing mode.
