### ISSUE TITLE
Can not swipe to go back

### ISSUE THREAD

**Issue by MohamedElzohirey** [jerkoch/SwipeCellKit#403]
When use SwipeCellKit with collectionView, I can not swipe to go back using 'handleNavigationTransition'

Even I do not use the left to right swipe. How can I bypass this swipe action to the main view to handle the original action (back)

**Comment by eli7ah** [comment]
Same problem for `UItTableView`. No any interface solutions helps. Also returning `nil` in `editActionsForRowAt:indexPath:for:` not helping.
Is there any ideas to solve the problem?

**Comment by MohamedElzohirey** [comment]
@eli7ah  I could work with this issue by this commit
https://github.com/MohamedElzohirey/SwipeCellKit/commit/4f786ea99ae193278c45a2c6d00727e5c2ddbfb8
