### ISSUE TITLE
cell is not moving when swipe

### ISSUE THREAD

**Issue by koolfreak** [jerkoch/SwipeCellKit#432]
Hi, I followed the documentation on how to setup this but when i swipe the uiviewcollectioncell is not moving either right or left? though i see the action is showing but it is underneath the cell? what i am missing? thanks a lot

**Comment by RublevIgor123** [comment]
Hi. Were you able to overcome this problem?

**Comment by koolfreak** [comment]
yes, thanks, got it already thanks

**Comment by RublevIgor123** [comment]
You misunderstood, I also need to figure it out and need help

Is there a code example?
Or some quick message for me?

**Comment by koolfreak** [comment]
ah i just need to put all my cell components on a contentView and it is all working fine
