### ISSUE TITLE
Possibility to set the width of SwipeAction Buttons

### ISSUE THREAD

**Issue by baschte** [jerkoch/SwipeCellKit#7]
It would be great if i could set the `buttonWidth` of any `SwipeAction Button`. I got some problems if a label text is longer than other ones. maybe someone else find it useful as well.

**Comment by jerkoch** [comment]
Hey @baschte - I'm working on improving the button layout now.  It may address this issue for you.

**Comment by seenoevo** [comment]
Sorry to ask but has this already been implemented and committed?

I can't seem to find any properties that allow me to resize the SwipeAction button. My cell's height is too big, and as a result, the SwipeAction buttons are big, which enlarges the button's image.

I like to scale that down.

**Comment by baschte** [comment]
hey @seenoevo 
you have to checkout the SwipeTableOptions-Class. Here you can change the public values for `maximumButtonWidth`, `minimumButtonWidth ` and so on.

https://github.com/jerkoch/SwipeCellKit/blob/develop/Source/SwipeTableOptions.swift#L13-L43

**Comment by seenoevo** [comment]
@baschte 

thanks for the reply and guidance!

 I'll check it out when I get home

**Comment by baschte** [comment]
@seenoevo you´re welcome!

**Comment by seenoevo** [comment]
@baschte 

noob question again but how would I go about changing the size of the button image?

although the button width has shrunken, the image is still the same large size

**Comment by jerkoch** [comment]
Hey @seenoevo - You need to provide an appropriately sized image. Your image size should be roughly 25x25pt, so 50px for @2x resolution.
