### ISSUE TITLE
Change title name when swipe center of cell

### ISSUE THREAD

**Issue by mohsinalimat** [jerkoch/SwipeCellKit#8]
Hello,

I want to implement Change button title name and image when swipe center of cell move... Any idea ?

Thanks,
Mohsinali Matiya

**Comment by jerkoch** [comment]
Hey @mohsinalimat - Are you asking if you change a button title/image **after** the swipe actions have been revealed and are currently visible? If so, that's not currently possible.

**Comment by mohsinalimat** [comment]
if suppose, button is greater then width then change the title i want excectly...

**Comment by jerkoch** [comment]
@mohsinalimat Yep, got it.  I had previously thought about adding a `SwipeTableViewCellDelegate` method to provide this type of hook.  It would allow you to do subtle animations like how the News.app buttons scale as they're exposed.  I'll open a new issue to track this enhancement.

**Comment by jerkoch** [comment]
Opened #9
